# Generated by Django 4.2.4 on 2023-09-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolStoreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=250, unique=True)),
                ('course', models.CharField(max_length=250, unique=True)),
                ('purpose', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
