# Generated by Django 4.2.4 on 2023-09-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolStoreApp', '0002_departmentcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentcourse',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='departmentcourse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolStoreApp.department'),
        ),
        migrations.CreateModel(
            name='StudDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_dob', models.DateField()),
                ('stud_age', models.IntegerField()),
                ('stud_gender', models.CharField(max_length=20)),
                ('stud_phno', models.IntegerField(unique=True)),
                ('stud_email', models.EmailField(max_length=254, unique=True)),
                ('stud_address', models.CharField(max_length=250, unique=True)),
                ('purpose', models.CharField(max_length=250)),
                ('materials', models.CharField(max_length=250)),
                ('stud_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolStoreApp.departmentcourse')),
                ('stud_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolStoreApp.department')),
            ],
        ),
    ]
