# Generated by Django 4.2.4 on 2023-09-06 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolStoreApp', '0003_remove_departmentcourse_purpose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='purposes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purposes', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='studdetails',
            name='materials',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studdetails',
            name='stud_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studdetails',
            name='stud_gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studdetails',
            name='stud_phno',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='studdetails',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolStoreApp.purposes'),
        ),
    ]
