# Generated by Django 4.2.4 on 2023-09-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolStoreApp', '0004_purposes_alter_studdetails_materials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studdetails',
            old_name='materials',
            new_name='Exam_Papers',
        ),
        migrations.AddField(
            model_name='studdetails',
            name='Notebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studdetails',
            name='Pen',
            field=models.BooleanField(default=False),
        ),
    ]
