# Generated by Django 4.2.4 on 2023-09-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolStoreApp', '0005_rename_materials_studdetails_exam_papers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studdetails',
            name='stud_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
