# Generated by Django 4.2.4 on 2023-09-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolStoreApp', '0006_alter_studdetails_stud_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studdetails',
            name='purpose',
            field=models.CharField(choices=[('E', 'Enquiry'), ('P', 'Place Order'), ('R', 'Return')], max_length=1),
        ),
        migrations.DeleteModel(
            name='purposes',
        ),
    ]
