# Generated by Django 4.2.4 on 2023-09-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolStoreApp', '0009_rename_course_studdetails_stud_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentcourse',
            old_name='department',
            new_name='dep_name',
        ),
        migrations.RenameField(
            model_name='studdetails',
            old_name='stud_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studdetails',
            old_name='department',
            new_name='dep_name',
        ),
    ]
