# Generated by Django 4.2.4 on 2023-09-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolStoreApp', '0012_alter_studdetails_stud_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studdetails',
            name='stud_dob',
            field=models.DateField(),
        ),
    ]
