# Generated by Django 4.2.4 on 2023-09-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolStoreApp', '0013_alter_studdetails_stud_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studdetails',
            name='stud_address',
            field=models.CharField(max_length=250),
        ),
    ]
