# Generated by Django 4.2.4 on 2023-09-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolStoreApp', '0014_alter_studdetails_stud_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studdetails',
            name='stud_dob',
            field=models.DateField(auto_now_add=True),
        ),
    ]
